// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package demo is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	CreateRoomReq
	CreateRoomRsp
	EnterRoomReq
	EnterRoomRsp
	Cards
	PlayCardReq
	PlayCardRsp
	Test
*/
package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreateRoomReq struct {
	UserID           *string `protobuf:"bytes,1,req,name=UserID" json:"UserID,omitempty"`
	RoomType         *int32  `protobuf:"varint,2,req,name=RoomType,def=1" json:"RoomType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoomReq) Reset()                    { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()               {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_CreateRoomReq_RoomType int32 = 1

func (m *CreateRoomReq) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *CreateRoomReq) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return Default_CreateRoomReq_RoomType
}

type CreateRoomRsp struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	RoomNum          *string `protobuf:"bytes,2,req,name=RoomNum" json:"RoomNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoomRsp) Reset()                    { *m = CreateRoomRsp{} }
func (m *CreateRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRsp) ProtoMessage()               {}
func (*CreateRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRoomRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *CreateRoomRsp) GetRoomNum() string {
	if m != nil && m.RoomNum != nil {
		return *m.RoomNum
	}
	return ""
}

type EnterRoomReq struct {
	UserID           *string `protobuf:"bytes,1,req,name=UserID" json:"UserID,omitempty"`
	RoomType         *int32  `protobuf:"varint,2,req,name=RoomType,def=1" json:"RoomType,omitempty"`
	RoomNum          *string `protobuf:"bytes,3,req,name=RoomNum" json:"RoomNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterRoomReq) Reset()                    { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()               {}
func (*EnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_EnterRoomReq_RoomType int32 = 1

func (m *EnterRoomReq) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *EnterRoomReq) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return Default_EnterRoomReq_RoomType
}

func (m *EnterRoomReq) GetRoomNum() string {
	if m != nil && m.RoomNum != nil {
		return *m.RoomNum
	}
	return ""
}

type EnterRoomRsp struct {
	Code             *int32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnterRoomRsp) Reset()                    { *m = EnterRoomRsp{} }
func (m *EnterRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomRsp) ProtoMessage()               {}
func (*EnterRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterRoomRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

type Cards struct {
	Card             []int32 `protobuf:"varint,1,rep,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Cards) Reset()                    { *m = Cards{} }
func (m *Cards) String() string            { return proto.CompactTextString(m) }
func (*Cards) ProtoMessage()               {}
func (*Cards) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Cards) GetCard() []int32 {
	if m != nil {
		return m.Card
	}
	return nil
}

type PlayCardReq struct {
	Card             *Cards `protobuf:"bytes,1,req,name=card" json:"card,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayCardReq) Reset()                    { *m = PlayCardReq{} }
func (m *PlayCardReq) String() string            { return proto.CompactTextString(m) }
func (*PlayCardReq) ProtoMessage()               {}
func (*PlayCardReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayCardReq) GetCard() *Cards {
	if m != nil {
		return m.Card
	}
	return nil
}

type PlayCardRsp struct {
	Code             *int32 `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayCardRsp) Reset()                    { *m = PlayCardRsp{} }
func (m *PlayCardRsp) String() string            { return proto.CompactTextString(m) }
func (*PlayCardRsp) ProtoMessage()               {}
func (*PlayCardRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayCardRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

type Test struct {
	Label            *string             `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32              `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64             `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *Test_OptionalGroup `protobuf:"group,4,opt,name=OptionalGroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetOptionalgroup() *Test_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type Test_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test_OptionalGroup) Reset()                    { *m = Test_OptionalGroup{} }
func (m *Test_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*Test_OptionalGroup) ProtoMessage()               {}
func (*Test_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *Test_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRoomReq)(nil), "demo.CreateRoomReq")
	proto.RegisterType((*CreateRoomRsp)(nil), "demo.CreateRoomRsp")
	proto.RegisterType((*EnterRoomReq)(nil), "demo.EnterRoomReq")
	proto.RegisterType((*EnterRoomRsp)(nil), "demo.EnterRoomRsp")
	proto.RegisterType((*Cards)(nil), "demo.Cards")
	proto.RegisterType((*PlayCardReq)(nil), "demo.PlayCardReq")
	proto.RegisterType((*PlayCardRsp)(nil), "demo.PlayCardRsp")
	proto.RegisterType((*Test)(nil), "demo.Test")
	proto.RegisterType((*Test_OptionalGroup)(nil), "demo.Test.OptionalGroup")
}

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x86, 0xc9, 0xcc, 0xe4, 0xfb, 0xec, 0x69, 0x47, 0x25, 0x52, 0x88, 0x3f, 0x8b, 0x21, 0x0b,
	0xc9, 0x6a, 0xc4, 0x22, 0x14, 0xba, 0x6d, 0x55, 0xdc, 0xa8, 0x94, 0x7a, 0x01, 0xd1, 0x1c, 0x4a,
	0x61, 0xa6, 0x49, 0x93, 0x74, 0xd1, 0x9b, 0xf0, 0x9a, 0x25, 0x33, 0xa5, 0x4c, 0xdd, 0xb9, 0x3d,
	0x4f, 0xde, 0xf7, 0x39, 0x39, 0xd0, 0xab, 0xfd, 0xb2, 0xb4, 0xce, 0x04, 0xc3, 0x32, 0x8d, 0xb5,
	0x11, 0x0f, 0x90, 0x4f, 0x1d, 0xaa, 0x80, 0x73, 0x63, 0xea, 0x39, 0x6e, 0xd8, 0x29, 0xfc, 0xfb,
	0xf0, 0xe8, 0x5e, 0x66, 0x9c, 0x14, 0x89, 0xec, 0xb1, 0x0b, 0x38, 0x89, 0x68, 0xb1, 0xb3, 0xc8,
	0x93, 0x22, 0x91, 0x74, 0x42, 0xee, 0x45, 0x79, 0x94, 0xf2, 0x96, 0x0d, 0x20, 0x9b, 0x1a, 0x8d,
	0x4d, 0x86, 0xb2, 0x33, 0xf8, 0x1f, 0xc1, 0xeb, 0xb6, 0x6e, 0x22, 0x3d, 0x31, 0x83, 0xc1, 0xe3,
	0x3a, 0xa0, 0xfb, 0x8b, 0xa4, 0xdb, 0x92, 0x36, 0x2d, 0x37, 0xdd, 0x96, 0x56, 0xfa, 0x75, 0x90,
	0x8a, 0x21, 0xd0, 0xa9, 0x72, 0xda, 0x37, 0x63, 0xe5, 0x34, 0x27, 0x45, 0x2a, 0xa9, 0x90, 0xd0,
	0x7f, 0xaf, 0xd4, 0x2e, 0xa2, 0x68, 0xbe, 0x3c, 0xc0, 0x44, 0xf6, 0x47, 0xfd, 0x32, 0x1e, 0xa1,
	0x6c, 0x72, 0xe2, 0xba, 0xf3, 0xf2, 0xf7, 0x97, 0xc4, 0x37, 0x81, 0x6c, 0x81, 0x3e, 0xb0, 0x1c,
	0x68, 0xa5, 0x3e, 0xb1, 0xda, 0x6f, 0x7e, 0x0e, 0x59, 0x68, 0xb7, 0x26, 0x92, 0x4e, 0x92, 0xf1,
	0x38, 0xe6, 0x1c, 0x5a, 0xcf, 0xd3, 0x22, 0x95, 0x29, 0xbb, 0x83, 0xdc, 0xd8, 0xb0, 0x32, 0x6b,
	0x55, 0x2d, 0x9d, 0xd9, 0x5a, 0x9e, 0x15, 0x44, 0xc2, 0x88, 0xb7, 0xe2, 0xd8, 0x58, 0xbe, 0xed,
	0xf9, 0x73, 0xe4, 0x57, 0xb7, 0x90, 0x1f, 0x0d, 0xd8, 0x10, 0xf2, 0x39, 0x6e, 0xb6, 0x2b, 0x87,
	0xfa, 0x69, 0x85, 0x95, 0xe6, 0x34, 0x8a, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x72, 0x9d,
	0x55, 0xca, 0x01, 0x00, 0x00,
}
